#!/bin/bash
tmux new -s python3 -n REPL 'cd /data/repos/dshs/course-matrix/matrix; clear; fish' \; splitw -v -p 33 -t 1 -c '/data/repos/dshs/course-matrix/matrix' python3  \; splitw -h -p 40 -t 2 fish \; neww -n CMD fish \; neww -n ncmpcpp ncmpcpp \; selectw -t 1 \; selectp -t 1 \; attach

