#!/bin/bash
tmux new -s matrix -n python3 'cd /data/repos/dshs/course-matrix/matrix; clear; fish' \; splitw -v -p 33 -t 1 -c '/data/repos/dshs/course-matrix/matrix' python3  \; splitw -h -p 40 -t 2 -c '/data/repos/dshs/course-matrix/matrix' fish \; selectw -t 1 \; selectp -t 1 \; attach

