#!/bin/bash
tmux new -s python3 -n IPython3 'cd /data/repos/dshs/course-matrix/matrix; clear; fish' \; splitw -v -p 33 -t 1 -c '/data/repos/dshs/course-matrix/matrix' ipython3  \; splitw -h -p 40 -t 2 -c '/data/repos/dshs/course-matrix/matrix' python3 \; neww -n ncmpcpp ncmpcpp \; selectw -t 1 \; selectp -t 1 \; attach

